/*
 * GENERATED — do not edit by hand.
 * Produced by 'just regen-types': typeshare over the mergequeue backend
 * crate. Re-run after any backend type change.
 */

// Rust newtypes typeshare can't emit:
export type Uuid = string;

/*
 Generated by typeshare 1.13.4
*/

/**
 * Batch lifecycle as an explicit finite state machine. The value is persisted
 * to `batches.state`; the engine resumes after a crash by re-dispatching the
 * current state, so each transition writes state *before* its GitHub side
 * effect. Transitions:
 * 
 * ```text
 * Staging --staged--> Testing --green--> Merging --ff--> Merged*
 * |  \--red--> Bisecting --1 left--> Ejected*
 * |                       \-->1----> Staging (smaller batch)
 * \--base moved--> Superseded*
 * ```
 * (* = terminal)
 */
export enum BatchState {
	/** Assembling the staging branch (base + each PR applied). */
	Staging = "staging",
	/** Staging pushed; awaiting required checks. */
	Testing = "testing",
	/** Checks green; fast-forwarding base. */
	Merging = "merging",
	/** Checks red; narrowing to the culprit PR. */
	Bisecting = "bisecting",
	/** Terminal: landed on base. */
	Merged = "merged",
	/** Terminal: a culprit was ejected; the remainder was re-queued. */
	Ejected = "ejected",
	/** Terminal: base moved or the batch was abandoned; entries re-queued. */
	Superseded = "superseded",
}

/** A compact summary of a queue's in-flight batch. */
export interface ActiveBatchView {
	id: string;
	state: BatchState;
	prs: number[];
}

/** Create a queue: a name plus optional config overriding the repo's default queue. */
export interface CreateQueueRequest {
	name: string;
	baseBranch?: string;
	batchSize?: number;
}

export interface EnqueueRequest {
	prNumber: number;
}

/** A PR's place in the merge lifecycle — projected from its entry + batch. */
export enum PrStatus {
	Queued = "queued",
	Testing = "testing",
	Merging = "merging",
	Blocked = "blocked",
	Merged = "merged",
	Ejected = "ejected",
}

export interface EntryView {
	id: string;
	prNumber: number;
	position: number;
	status: PrStatus;
}

export interface Health {
	status: string;
}

/** What happened to one PR in a finished batch run, snapshotted into the ledger. */
export enum LedgerEntryResult {
	/** The PR landed on the base branch with its batch. */
	Landed = "landed",
	/** The PR was identified as the batch breaker and removed from the queue. */
	Ejected = "ejected",
	/** The PR went back to the queue to be retried in a later batch. */
	Requeued = "requeued",
	/**
	 * The PR was manually pulled from its in-flight batch (dashboard remove or
	 * a PR-close webhook) — it left the queue rather than going back to it.
	 */
	Removed = "removed",
}

/** One PR's fate within a finished batch run, projected from the ledger. */
export interface LedgerEntryView {
	prNumber: number;
	result: LedgerEntryResult;
}

/** Terminal outcome recorded in the append-only `queue_ledger` table. */
export enum LedgerOutcome {
	/** All PRs in the batch landed on the base branch. */
	Merged = "merged",
	/** A culprit PR was ejected; the remainder was re-queued. */
	Ejected = "ejected",
	/** The batch was abandoned because the base moved or it was overtaken. */
	Superseded = "superseded",
}

/** One finished batch run from the append-only ledger (the dashboard's history view). */
export interface LedgerView {
	id: string;
	batchId: string;
	outcome: LedgerOutcome;
	baseSha: string;
	landedSha?: string;
	ejectedPr?: number;
	entries: LedgerEntryView[];
	startedAt: string;
	endedAt: string;
}

/** The signed-in GitHub user, for the dashboard's auth gate. */
export interface MeView {
	login: string;
	avatarUrl: string;
}

/** An open PR — a candidate to add to the queue. */
export interface PrView {
	number: number;
	title: string;
	headRef: string;
	baseRef: string;
	mergeable?: boolean;
}

/**
 * One named queue with its config + live depth. `active` is the active-batch
 * summary; it's populated by the per-repo queues endpoint and left `None` in the
 * lightweight repo switcher.
 */
export interface QueueView {
	id: string;
	repoId: string;
	name: string;
	baseBranch: string;
	batchSize: number;
	depth: number;
	active?: ActiveBatchView;
}

/** Drag-to-reorder: the queued entry ids in their new order (front of the train first). */
export interface ReorderRequest {
	entryIds: string[];
}

/** A repo under management, with its named queues (the dashboard's switcher). */
export interface RepoView {
	id: string;
	owner: string;
	name: string;
	queues: QueueView[];
}

/** Where the resolved GitHub App credentials came from. */
export enum SetupSource {
	/** Static credentials from config/env (the static escape hatch). */
	Config = "config",
	/** Credentials minted by the `/setup` manifest flow, stored in the DB. */
	Manifest = "manifest",
}

/**
 * Whether the GitHub App is registered. Drives the dashboard's setup gate so the
 * manifest flow is offered only when the App is missing.
 */
export interface SetupStatus {
	registered: boolean;
	/** Where to start the manifest flow (always present, used by the "connect" CTA). */
	setupUrl: string;
	slug?: string;
	installUrl?: string;
	manageUrl?: string;
	source?: SetupSource;
}

/** Lifecycle of a single queued PR. */
export enum EntryState {
	/** Waiting in line. */
	Queued = "queued",
	/** Part of the batch currently being staged/tested. */
	Testing = "testing",
	/** Landed on the base branch. */
	Merged = "merged",
	/** Removed from the queue after being identified as the batch breaker. */
	Ejected = "ejected",
}

export enum MergeMethod {
	Squash = "squash",
	Merge = "merge",
	Rebase = "rebase",
}

