/*
 * GENERATED — do not edit by hand.
 * Produced by 'just regen-types': typeshare over the mergequeue backend
 * crate. Re-run after any backend type change.
 */

// Rust newtypes typeshare can't emit:
export type Uuid = string;

/*
 Generated by typeshare 1.13.4
*/

export interface EnqueueRequest {
	prNumber: number;
}

/** A PR's place in the merge lifecycle — projected from its entry + batch. */
export enum PrStatus {
	Queued = "queued",
	Testing = "testing",
	Merging = "merging",
	Blocked = "blocked",
	Merged = "merged",
	Ejected = "ejected",
}

export interface EntryView {
	id: string;
	prNumber: number;
	position: number;
	status: PrStatus;
}

export interface Health {
	status: string;
}

/** The signed-in GitHub user, for the dashboard's auth gate. */
export interface MeView {
	login: string;
	avatarUrl: string;
}

/** An open PR — a candidate to add to the queue. */
export interface PrView {
	number: number;
	title: string;
	headRef: string;
	baseRef: string;
	mergeable?: boolean;
}

/** Drag-to-reorder: the queued entry ids in their new order (front of the train first). */
export interface ReorderRequest {
	entryIds: string[];
}

/** A repo under management, with its live queue depth. */
export interface RepoView {
	id: string;
	owner: string;
	name: string;
	baseBranch: string;
	batchSize: number;
	queued: number;
}

/** Where the resolved GitHub App credentials came from. */
export enum SetupSource {
	/** Static credentials from config/env (the static escape hatch). */
	Config = "config",
	/** Credentials minted by the `/setup` manifest flow, stored in the DB. */
	Manifest = "manifest",
}

/**
 * Whether the GitHub App is registered. Drives the dashboard's setup gate so the
 * manifest flow is offered only when the App is missing.
 */
export interface SetupStatus {
	registered: boolean;
	/** Where to start the manifest flow (always present, used by the "connect" CTA). */
	setupUrl: string;
	slug?: string;
	installUrl?: string;
	manageUrl?: string;
	source?: SetupSource;
}

/**
 * Batch lifecycle as an explicit finite state machine. The value is persisted
 * to `batches.state`; the engine resumes after a crash by re-dispatching the
 * current state, so each transition writes state *before* its GitHub side
 * effect. Transitions:
 * 
 * ```text
 * Staging --staged--> Testing --green--> Merging --ff--> Merged*
 * |  \--red--> Bisecting --1 left--> Ejected*
 * |                       \-->1----> Staging (smaller batch)
 * \--base moved--> Superseded*
 * ```
 * (* = terminal)
 */
export enum BatchState {
	/** Assembling the staging branch (base + each PR applied). */
	Staging = "staging",
	/** Staging pushed; awaiting required checks. */
	Testing = "testing",
	/** Checks green; fast-forwarding base. */
	Merging = "merging",
	/** Checks red; narrowing to the culprit PR. */
	Bisecting = "bisecting",
	/** Terminal: landed on base. */
	Merged = "merged",
	/** Terminal: a culprit was ejected; the remainder was re-queued. */
	Ejected = "ejected",
	/** Terminal: base moved or the batch was abandoned; entries re-queued. */
	Superseded = "superseded",
}

/** Lifecycle of a single queued PR. */
export enum EntryState {
	/** Waiting in line. */
	Queued = "queued",
	/** Part of the batch currently being staged/tested. */
	Testing = "testing",
	/** Landed on the base branch. */
	Merged = "merged",
	/** Removed from the queue after being identified as the batch breaker. */
	Ejected = "ejected",
}

export enum MergeMethod {
	Squash = "squash",
	Merge = "merge",
	Rebase = "rebase",
}

